/**
 * GENERIC — extraction target for `@open-elements/nextjs-app-layer`.
 *
 * Renders the source of the minimal, hand-written service worker as a string. The prebuild script
 * writes the result to `public/sw.js`, injecting the content-hash of `offline.html` as the cache
 * version so the cache only changes when the offline page changes.
 *
 * Behavior (see `docs/specs/111-pwa-support/design.md`):
 * - precache exactly the offline page;
 * - `fetch` handles ONLY navigation requests, network-first, falling back to the precached offline
 *   page on error; everything else passes through untouched and uncached;
 * - `skipWaiting()` + `clients.claim()` so a new worker activates immediately;
 * - old caches (different version) are deleted on activate.
 */
export interface ServiceWorkerOptions {
  /** Cache version — the content hash of the offline page. */
  readonly cacheVersion: string;
  /** URL of the precached offline page; defaults to "/offline.html". */
  readonly offlineUrl?: string;
  /** Cache-name prefix; defaults to "oe-offline". */
  readonly cachePrefix?: string;
}

/**
 * @param options cache version + optional offline URL / prefix
 * @return the service-worker JavaScript source
 */
export function renderServiceWorker(options: ServiceWorkerOptions): string {
  const offlineUrl = options.offlineUrl ?? "/offline.html";
  const cachePrefix = options.cachePrefix ?? "oe-offline";
  return `// Generated by scripts/generate-pwa-assets.mjs — do not edit by hand.
const CACHE = ${JSON.stringify(`${cachePrefix}-${options.cacheVersion}`)};
const OFFLINE_URL = ${JSON.stringify(offlineUrl)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.add(OFFLINE_URL)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  // Only navigation requests are handled; everything else (API, auth, assets, OIDC) passes through.
  if (event.request.mode !== "navigate") {
    return;
  }
  event.respondWith(
    fetch(event.request).catch(() => caches.match(OFFLINE_URL))
  );
});
`;
}
