ALTER TABLE companies ADD COLUMN bank_name VARCHAR(255);
ALTER TABLE companies ADD COLUMN bic VARCHAR(11);
ALTER TABLE companies ADD COLUMN iban VARCHAR(34);
ALTER TABLE companies ADD COLUMN vat_id VARCHAR(20);
