package com.openelements.crm.updates;

public enum UpdateType {
    COMPANY_CREATED, COMPANY_UPDATED, COMPANY_DELETED,
    CONTACT_CREATED, CONTACT_UPDATED, CONTACT_DELETED,
    COMPANY_COMMENT_CREATED, COMPANY_COMMENT_UPDATED, COMPANY_COMMENT_DELETED,
    CONTACT_COMMENT_CREATED, CONTACT_COMMENT_UPDATED, CONTACT_COMMENT_DELETED
}
